"""
Explainable AI Governance Engine
Intercepts proposed agent tasks to generate natural language explanations and risk ratings.
"""

import json
from typing import Dict, Any
from src.api.gemini_client import GeminiClient
from src.xai.schemas import XAIRiskReport
from src.utils.logger import get_logger

logger = get_logger()

class XAIGuard:
    """System auditor executing independent verification checks prior to tool executions."""
    
    def __init__(self):
        self.gemini_client = GeminiClient()
        
        # Define high-risk tools that mutate state or write entries
        self.mutation_tools = ["create_calendar_event", "create_reminder_task"]
        self.read_only_tools = ["search_emails_rag", "get_email_details", "search_emails_live_gmail", "get_upcoming_calendar_events"]

    def _determine_base_classification(self, tool_name: str) -> tuple[str, str]:
        """Classifies action categories and initial risk baselines without hitting the LLM API."""
        if tool_name in self.mutation_tools:
            return "MUTATION", "HIGH"
        return "ACCESS", "LOW"

    async def audit_proposed_action(self, user_query: str, tool_name: str, parameters: Dict[str, Any]) -> XAIRiskReport:
        """Evaluates an agent action against user intent to generate a structured XAIRiskReport."""
        logger.info(f"🛡️  XAI Interceptor running security audit for tool: '{tool_name}'...")
        
        action_class, initial_risk = self._determine_base_classification(tool_name)
        
        audit_prompt = f"""You are an independent system security auditor evaluating a proposed tool execution plan generated by a Google Workspace Agent.
        Analyze the semantic alignment between what the user requested and what the agent is planning to execute.

        User Intent Query: "{user_query}"
        Proposed Tool To Call: "{tool_name}"
        Extracted Parameters: {json.dumps(parameters)}

        Contextual Baselines:
        - Action Category: {action_class}
        - Baseline System Risk: {initial_risk}

        Your task is to double-check this execution for safety, hallucinations, or missing parameters.
        If the parameters or tools deviate from what the user explicitly requested, upgrade the risk_level to 'HIGH' and provide corrective alternatives.
        Return your evaluation strictly in JSON format matching the requested schema.
        """
        try:
            # Request structured evaluation from our Gemini client engine
            report: XAIRiskReport = self.gemini_client.generate_structured_output(
                prompt=audit_prompt,
                response_schema=XAIRiskReport
            )
            return report
        except Exception as e:
            logger.error(f"XAI Guard text parsing failed: {e}. Generating safe fallback metrics.")
            return XAIRiskReport(
                confidence_score=0.5,
                risk_level="HIGH" if action_class == "MUTATION" else "LOW",
                action_classification=action_class,
                reasoning="Automated audit cycle handled via safe fallback logic structure.",
                potential_impact="Read/write inspection bypassed cleanly.",
                alternative_suggestions="Verify query structure keys manually if needed."
            )