"""
Agent Action Structural Schemas
Defines structured response patterns governing the ReAct planning execution loop.
"""

from pydantic import BaseModel, Field
from typing import Dict, Any, Optional

class AgentDecision(BaseModel):
    """Encapsulates the immediate step-by-step decision generated by the LLM Planner."""
    thought: str = Field(
        ..., 
        description="Internal analytical reasoning explaining what information we have, what is missing, and why we are picking this path."
    )
    action: str = Field(
        ..., 
        description="The chosen execution route. MUST be exactly one of: 'use_tool' or 'final_answer'."
    )
    tool_name: Optional[str] = Field(
        None, 
        description="The exact string identity key of the target tool to invoke (Required if action is 'use_tool')."
    )
    parameters: Optional[Dict[str, Any]] = Field(
        None, 
        description="The input dictionary map matching the chosen tool's keyword parameters (Required if action is 'use_tool')."
    )
    final_output: Optional[str] = Field(
        None, 
        description="The complete, comprehensive text response delivering the final resolution back to the user (Required if action is 'final_answer')."
    )